export const GET_ACCOUNT_DATA = 'GET_ACCOUNT_DATA'
export const GET_ACCOUNT_DATA_F = 'GET_ACCOUNT_DATA_F'
export const GET_ACCOUNT_DATA_R = 'GET_ACCOUNT_DATA_R'

export const GET_POSTS_ALL = 'GET_POSTS_ALL'
export const GET_POSTS_ALL_F = 'GET_POSTS_ALL_F'
export const GET_POSTS_ALL_R = 'GET_POSTS_ALL_R'

export const GET_POSTS_DETAIL = 'GET_POSTS_DETAIL'
export const GET_POSTS_DETAIL_F = 'GET_POSTS_DETAIL_F'
export const GET_POSTS_DETAIL_R = 'GET_POSTS_DETAIL_R'

export const GET_USERS_ALL = 'GET_USERS_ALL'
export const GET_USERS_ALL_F = 'GET_USERS_ALL_F'
export const GET_USERS_ALL_R = 'GET_USERS_ALL_R'

export const GET_USER_DETAIL = 'GET_USER_DETAIL'
export const GET_USER_DETAIL_F = 'GET_USER_DETAIL_F'
export const GET_USER_DETAIL_R = 'GET_USER_DETAIL_R'

export const GET_USER_ALBUM = 'GET_USER_ALBUM'
export const GET_USER_ALBUM_F = 'GET_USER_ALBUM_F'
export const GET_USER_ALBUM_R = 'GET_USER_ALBUM_R'

export const GET_USER_PHOTO = 'GET_USER_PHOTO'
export const GET_USER_PHOTO_F = 'GET_USER_PHOTO_F'
export const GET_USER_PHOTO_R = 'GET_USER_PHOTO_R'

export const ADD_NEW_POST = 'ADD_NEW_POST'
export const ADD_NEW_POST_F = 'ADD_NEW_POST_F'
export const ADD_NEW_POST_R = 'ADD_NEW_POST_R'

export const EDIT_POST = 'EDIT_POST'
export const EDIT_POST_F = 'EDIT_POST_F'
export const EDIT_POST_R = 'EDIT_POST_R'

export const DELETE_POST = 'DELETE_POST'
export const DELETE_POST_F = 'DELETE_POST_F'
export const DELETE_POST_R = 'DELETE_POST_R'

export const ADD_NEW_COMMENT = 'ADD_NEW_COMMENT'
export const ADD_NEW_COMMENT_F = 'ADD_NEW_COMMENT_F'
export const ADD_NEW_COMMENT_R = 'ADD_NEW_COMMENT_R'

export const EDIT_COMMENT = 'EDIT_COMMENT'
export const EDIT_COMMENT_F = 'EDIT_COMMENT_F'
export const EDIT_COMMENT_R = 'EDIT_COMMENT_R'

export const DELETE_COMMENT = 'DELETE_COMMENT'
export const DELETE_COMMENT_F = 'DELETE_COMMENT_F'
export const DELETE_COMMENT_R = 'DELETE_COMMENT_R'
